version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.2 # Dynamic config must be enabled. See https://circleci.com/docs/2.0/dynamic-config

workflows:
  version: 2
  check-for-changes:
    jobs:
      - path-filtering/filter:
          name: check-for-changes
          mapping: |
            workload-allocation-handler/.* workflow-directory "workload-allocation-handler"
            pre-sentence-report-handler/.* workflow-directory "pre-sentence-report-handler"
